version: '3.9'

services:
  postgres-age:
    image: apache/age:latest
    container_name: postgres_age
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - .:/age/regress/age_load/data/project
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_app
    volumes:
      - .:/app
    environment:
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: root
      DB_HOST: postgres-age
      DB_PORT: 5432
    depends_on:
      - postgres-age
      
volumes:
  pg_data:

